name: Start app

on:
  schedule:
    - cron: '*/30 * * * *'  # This sets the action to run every 10 minutes
  workflow_dispatch:

concurrency: 
  group: start-app-group
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create keepalive file
      run: touch keepalive

    - name: Commit and push keepalive file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add keepalive
        git commit -m "Add keepalive file"
        git push
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    #- name: Download ngrok
    #  run: wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

    - name: Install ngrok
      run: |
        unzip -o ngrok-stable-linux-amd64.zip
        ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}

    - name: Start Flask app
      run: |
        nohup python app.py &
      env:
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}

    - name: Start ngrok
      run: |
        nohup ./ngrok http 5000 &
        sleep 10 # Give ngrok some time to establish the tunnel
        NGROK_TUNNEL_URL=$(curl --silent --max-time 10 http://localhost:4040/api/tunnels | jq .tunnels[0].public_url)
        echo "Ngrok tunnel URL: $NGROK_TUNNEL_URL"
        while true; do
          echo "Keeping the workflow running..."
          sleep 600 # Sleep for 10 minutes
        done
